import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./Providers"; 
import "./globals.css";
import Script from "next/script"; // 1. Importamos Script


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prompterio",
  description: "Generated by AOCO",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {children}
        </Providers>

        
      </body>
    </html>
  );
}



